-- Farm Delivery Database DDL
CREATE DATABASE FarmDelivaryDB;
GO
USE FarmDelivaryDB;
GO

-- Tables
CREATE TABLE CROP_TYPE (
    CROPTYPEID INT PRIMARY KEY,
    CROPCATEGORY VARCHAR(40) NOT NULL
);

CREATE TABLE DRIVER (
    DRIVERID INT PRIMARY KEY,
    DRIVERNAME VARCHAR(30) NOT NULL,
    LICENSENUMBER NUMERIC(30, 0) NOT NULL
);

CREATE TABLE TRUCK (
    TRUCK_ID INT PRIMARY KEY,
    TRUCK_REG VARCHAR(50) NOT NULL,
    CAPACITY_KG FLOAT NOT NULL
);

CREATE TABLE FARM (
    FARMID INT PRIMARY KEY,
    FARM_NAME VARCHAR(30) NOT NULL,
    LOCATION VARCHAR(30) NULL,
    CITY VARCHAR(30) NULL
);

CREATE TABLE RESTAURANT (
    RESTAURANTID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DELIVERY_ADDRESS VARCHAR(50) NOT NULL,
    DELIVER_WINDOW DATETIME2 NULL,
    CITY VARCHAR(50) NULL
);

CREATE TABLE DELIVARY_TRIP (
    TRIPID INT PRIMARY KEY,
    DRIVERID INT NOT NULL REFERENCES DRIVER(DRIVERID),
    TRUCK_ID INT NOT NULL REFERENCES TRUCK(TRUCK_ID),
    TRIP_DATE DATETIME2 NOT NULL,
    ROUTE_NAME VARCHAR(50) NOT NULL,
    TOTAL_DISTANCE FLOAT NULL
);

CREATE TABLE FARM_SPECIALIZATION (
    CROPTYPEID INT NOT NULL REFERENCES CROP_TYPE(CROPTYPEID),
    FARMID INT NOT NULL REFERENCES FARM(FARMID),
    PRIMARY KEY (CROPTYPEID, FARMID)
);

CREATE TABLE HARVEST_BATCH (
    FARMID INT NOT NULL REFERENCES FARM(FARMID),
    BATCHID INT NOT NULL,
    CROPTYPEID INT NOT NULL REFERENCES CROP_TYPE(CROPTYPEID),
    HARVEST_DATE DATETIME2 NOT NULL,
    AVAILABLE_QTY NUMERIC(30, 0) NOT NULL,
    UNIT_PRICE NUMERIC(30, 0) NOT NULL,
    PRIMARY KEY (FARMID, BATCHID)
);

CREATE TABLE ORDERS (
    RESTAURANTID INT NOT NULL REFERENCES RESTAURANT(RESTAURANTID),
    ORDERID INT NOT NULL,
    ORDER_DATE DATETIME2 NULL,
    ORDER_STATUS VARCHAR(30) NULL,
    PRIMARY KEY (RESTAURANTID, ORDERID)
);

CREATE TABLE ORDER_LINE (
    RESTAURANTID INT NOT NULL,
    ORDERID INT NOT NULL,
    ORDERLINEID INT NOT NULL,
    FARMID INT NOT NULL,
    BATCHID INT NOT NULL,
    QUANTITY NUMERIC(30, 0) NOT NULL,
    PRIMARY KEY (RESTAURANTID, ORDERID, ORDERLINEID)
);

CREATE TABLE DELIVARY_TRIP_LINE (
    TRIP_ID INT NOT NULL,
    ORDER_LINE_ID INT NOT NULL,
    TRIPID INT NOT NULL REFERENCES DELIVARY_TRIP(TRIPID),
    RESTAURANTID INT NOT NULL,
    ORDERID INT NOT NULL,
    ORDERLINEID INT NOT NULL,
    STOP_SEQUENCE INT NOT NULL,
    ACTUAL_DELIVERY_TIME DATETIME2 NOT NULL,
    PRIMARY KEY (TRIP_ID, ORDER_LINE_ID)
);
GO
